### ISSUE TITLE
Control motor pwm directly

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/quadrotor_control#12]
Currently, we use a PID controller to control the x,y,z velocity
It would be interesting to see what sort of control is seen when we do RL on the motor pwm directly

**Comment by AbdealiLoKo** [comment]
This is very easy - there is a rostopic `/cmd_vel` thats all :P

**Comment by kunalgrover05** [comment]
? /cmd_vel does only quad velocity control isn't it? The default mode is PWM mode we need to switch out of it to do PWM control.

**Comment by AbdealiLoKo** [comment]
Sorry - I wrote the wrong topic there - the topic for pwm is `/motor_pwm`

**Comment by nikhilkalige** [comment]
@AbdealiJK Where you able to figure out how to make use of `/motor_pwm`. I tried setting an array like `[100 100 100 100]` but it doesn't seem to make any change in the state.

**Comment by AbdealiLoKo** [comment]
@NikhilKalige - We did not pursue this further, as we found that using the `/cmd_vel` was more appropriate for our use case.

Although, I believe `/motor_pwm` is the right approach to it. You may still be using the wrong controller with the quadrotor ? You need to enable the quadrotor_propulsion mode (probably through roscontrol).
By default, the controller that the launch files use is the twist_controller.

You can find the relevant source code [here](https://github.com/tu-darmstadt-ros-pkg/hector_quadrotor/blob/8a7164535749f57fb2799464858ffee53ef0710c/hector_quadrotor_model/src/quadrotor_propulsion.cpp) for quadrotor_propulsion, where it shows that `/motor_pwm` is actually used.

There is also an interesting answer in answers.ros [here](http://answers.ros.org/question/53538/hector_quadrotor-not-responding-to-cmd_vel/) which describes how to switch off quadrotor_propulsion and also explains that quadrotor_propulsion needs MATLAB to run. I've not really tried this, but these discussions could be helpful to you.

**Comment by nikhilkalige** [comment]
I checked that, I believe it is enabled by default. When I update the `motor_pwm` topic, I am getting the debug statements from the code present in the file you mentioned, but it does not affect the model. 

Do you think `cmd_ve`l can be used to flip?

**Comment by AbdealiLoKo** [comment]
`cmd_vel` is directly related to `motor_pwm` ... they both are equivalent and are related by some math equations. As `cmd_vel` is of type Twist, yes, it should be able to flip the quadrotor as it has an angular velocity component.
