### ISSUE TITLE
hectorquad: `/cmd_vel` not working

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/quadrotor_control#21]
`/cmd_vel` doesnt seem to be able to control the robot - I think it worked before ... but apparently doesnt work anynmore

**Comment by AbdealiLoKo** [comment]
The reason for this is that the message (`geometry_msgs::Twist`) being sent into `cmd_vel`'s rostopic is a local variable. It seems that the `publish` function is asynchronous - and so it needs the variable to exist even after it is being called. Making this into a class variable solves the problem.

**Comment by AbdealiLoKo** [comment]
A few more notes:
- In current pegasus implementation - the max vels are +/-5 - this is insufficient to overcome gravity - hence the bot will always go down.
- This is the issue that made the sarsa weird sometimes. Its highly non deterministic because of memory clearing and stuff

**Comment by AbdealiLoKo** [comment]
Sorry - seems like I was mistaken this is not an issue.
I ran the program multiple times - and sometimes forgot to `make` it ... So, Had erroneous observations.

The problem is simply that the velocities given by pegasus were too small to  oversome gravity

**Comment by kunalgrover05** [comment]
Doesn't seem so. I tried running with z_vel=1 and it still goes up.
