### ISSUE TITLE
Quad control is broken

### ISSUE THREAD

**Issue by kunalgrover05** [AbdealiJK/quadrotor_control#23]
When I build the old version with Pegasus, it works, but here, if I hard-code the action values, it keeps going down.

**Comment by AbdealiLoKo** [comment]
My earlier assumption that cmd_vel works without a controller was wrong.
I am unsure on how to do this now.

**Comment by AbdealiLoKo** [comment]
Fixed in https://github.com/AbdealiJK/quadrotor_control/commit/4d2d541631eff9bbe2f96d2044e1a51d7a949f5c
