### ISSUE TITLE
System is still stochastic

### ISSUE THREAD

**Issue by kunalgrover05** [AbdealiJK/quadrotor_control#26]
Running the agent with the same initial conditions doesn't give same output always.
One reason could be the computation involved in finding action/gradient etc. Not sure whether it should matter so much.

**Comment by AbdealiLoKo** [comment]
What about when you set a constant velocity ?

**Comment by AbdealiLoKo** [comment]
I did the following experiments about this:
1. I set the action in `get_action` to 0 - and i printed the states in `get_action` - the states and their order were exactly the same (state = pos and vel) when I ran quad.launch twice
2. I set the `get_action` to the linear policy and printed the states in `get_action` - the states were again the exact same (state = pos and vel) when I ran quad.launch twice

So, its not stochastic.

**Comment by AbdealiLoKo** [comment]
If you were comparing the states from 2 diff policies - understandable this wont be the same as the actions taken will be different.

**Comment by kunalgrover05** [comment]
The initial policy is constant, so if steps were proper, the system would be deterministic at time t too(since none of the steps are stochastic). I didn't check the states after every x seconds but checked only the the final episode results which seem to change across different runs.

**Comment by AbdealiLoKo** [comment]
You're right - the episode rewards are different.
I notice that the changes happen only after the statement `[ INFO] [1441777378.532863418, 13.544000000]: Engaging motors!` - which doesnt always happen at the same time.

**Comment by AbdealiLoKo** [comment]
So ... I did a lot of digging around. And I think the major issue with this whole thing is that we;re using `cmd_vel` which is a topic - and hence it runs asynchronously. This means that if we do an action, it takes about a few miliseconds before it actually reaches gazebo.

So, if we want synchronous comms - we should always use services - never topics

**Comment by AbdealiLoKo** [comment]
Fixed in https://github.com/AbdealiJK/quadrotor_control/commit/8da6606d4d1ad881631f4e16710e09e972fc144d
