### ISSUE TITLE
Gazebo time is not same as rl_env time

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/quadrotor_control#8]
We need rl_env to tell gazebo when to run and when not to - how many timesteps to jump by and so on. 

Currently, gazebo runs at full speed and rl_env only uses the data once in a while. This is bad as it's not in sync

**Comment by AbdealiLoKo** [comment]
I think we'd need to use actionlib to ask gazebo to pause/unpause and give results.
http://answers.ros.org/question/11834/when-should-i-use-topics-vs-services-vs-actionlib-actions-vs-dynamic_reconfigure/

There is a rosservice for pausing and unpausing physics ... but we cannot specify how muchtime to pause/unpause

**Comment by AbdealiLoKo** [comment]
Asked in forums:
http://answers.ros.org/question/211774/pausing-and-unpausing-hector_quadrotor/
http://answers.ros.org/question/211774/pausing-and-unpausing-gazebo/
http://answers.gazebosim.org/question/8957/pausing-and-unpausing-gazebo-for-specific-times/

but no replies

**Comment by kunalgrover05** [comment]
If I understood it correctly from here(see flow diagram): http://gazebosim.org/tutorials/?tut=ros_control, Gazebo is more of a static interface. It is the controller that does the job. And this package called controller_manager gives us access to this controller. Not sure, trying it out.

**Comment by AbdealiLoKo** [comment]
I have written a partial solution in my branch `ajk/quad` - could you
continue it ?

What we need to do is whenever `sensation` is called -we unpause gazebo,
and wait for 1 second and then pause it again. Then we get the latest state
and use that.

Problem in my branch is that I set the unpause/pause time to be 1 second
and the topic for state is every 3 seconds. So, the state is actually
updated once in 3 actions.
What we need is to use a service to get the state of the current quadrotor
- topics arent suitable for this
